[package]
name = "atproto_pds"
version = "0.0.1"
description = ""
repository = "https://github.com/edjcase/motoko_atproto_pds"
keywords = ["at", "protocol", "atproto", "ipld"]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"liminal@3" = "3.1.0"
"base-x-encoder@2" = "2.1.0"
"dag-cbor@2" = "2.2.1"
"cid@1" = "1.1.0"
"did@3" = "3.1.0"
"json@1" = "1.4.0"
"xtended-text@2" = "2.3.0"
"tid@1" = "1.1.0"
"car@1" = "1.1.0"
"dag-pb@0" = "0.1.0"
"ic@3" = "3.2.0"
"datetime@1" = "1.1.0"
"xtended-iter@1" = "1.1.0"
"xtended-collections@0" = "0.2.0"
"url-kit@3" = "3.0.0"
"sha2@0" = "0.1.6"
"certified-assets@0" = "0.6.0"
"buffer@0" = "0.1.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
