[package]
name = "atproto-pds"
version = "0.0.1"
description = "A Motoko implementation of an AT Protocol Personal Data Server (PDS) made for DAOs."
repository = "https://github.com/edjcase/motoko_atproto_pds"
keywords = ["at", "protocol", "atproto", "ipld"]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"liminal@3" = "3.1.0"
"atproto@0" = "0.0.1"
"datetime@1" = "1.1.0"
"car@1" = "1.1.0"

[dev-dependencies]
test = "2.1.1"
bench = "1.0.0"
