[dependencies]
"core@1" = "1.0.0"
"dao-proposal-engine@2" = "2.1.0"
"ic@3" = "3.2.0"
"stableheapbtreemap@1" = "1.5.0"
"dag-cbor@2" = "2.2.1"
"atproto@0" = "../../../motoko_atproto/"
"icrc120-mo@0" = "../../../icrc120.mo/"
"icrc118-mo@0" = "../../../icrc118.mo/"
"class-plus@0" = "0.0.2"
"timer-tool@0" = "0.1.1"
"stable-local-log@0" = "0.1.1"
